name: Release
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    name: ${{ matrix.friendlyName }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        node: ["20.x"]
        os: [macos-12, windows-latest, ubuntu-20.04]
        arch: [x64]
        include:
          - os: macos-12
            friendlyName: macOS
          - os: windows-latest
            friendlyName: Windows
          - os: ubuntu-20.04
            friendlyName: Ubuntu
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: yarn install && cache
        uses: ./.github/actions/yarn-nm-install

      - name: Package application
        id: packageing
        run: yarn dist
        env:
          USE_HARD_LINKS: "false"

      - name: Publish
        id: publishing
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/NightPDF*.exe
            dist/NightPDF*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/latest*.yml
          draft: true
